name: Generate Contribution Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual run

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: GodwinWRaj # CHANGE THIS TO YOUR USERNAME
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Push Contribution Snake to the Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
